# Solid Queue configuration
development:
  dispatchers:
    - polling_interval: 1
      batch_size: 100
      concurrency_maintenance_interval: 300

  workers:
    - queues: "*"
      threads: 2
      processes: 1

test:
  dispatchers:
    - polling_interval: 1
      batch_size: 50
      concurrency_maintenance_interval: 300

  workers:
    - queues: "*"
      threads: 1
      processes: 1

docker:
  dispatchers:
    - polling_interval: 1
      batch_size: 100
      concurrency_maintenance_interval: 300

  workers:
    - queues: "*"
      threads: 2
      processes: 1

aws_test:
  dispatchers:
    - polling_interval: 1
      batch_size: 200
      concurrency_maintenance_interval: 600

  workers:
    - queues: "*"
      threads: 3
      processes: 1

production:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      concurrency_maintenance_interval: 600

  workers:
    - queues: "*"
      threads: 3
      processes: 1
